Repository vmware/govmomi, pull requests merged in 2018-05, with the labels that each got.

#1111 Add vmxnet2, pcnet32 and sriov to VirtualDeviceList.EthernetCardTypes
  object/virtual_device_list.go
  object/virtual_device_list_test.go
Labels: cla-not-required

#1110 vcsim: use VirtualDisk CapacityInKB for device summary
  simulator/virtual_machine.go
Labels: cla-not-required

#1109 Add STS support for token renewal
  govc/session/login.go
  sts/client.go
  sts/client_test.go
  sts/internal/types.go
  sts/internal/types_test.go
  sts/signer.go
Labels: cla-not-required

#1119 Fix govc vm.clone -annotation flag
  govc/test/vm.bats
  govc/vm/change.go
  govc/vm/clone.go
Labels: cla-not-required

#1120 vcsim: add STS simulator
  govc/session/login.go
  govc/test/session.bats
  sts/client.go
  sts/simulator/simulator.go
  vcsim/main.go
Labels: cla-not-required

#1122 Add devbox scripts
  govc/emacs/govc.el
  govc/flags/client.go
  govc/sso/service/ls.go
  govc/test/session.bats
  govc/test/sso.bats
  scripts/devbox/.gitignore
  scripts/devbox/README.md
  scripts/devbox/create.sh
  scripts/devbox/provision.sh
  scripts/devbox/vcp-local-up-cluster.sh
  scripts/vcsa/README.md
  scripts/vcsa/create-cluster.sh
  scripts/vcsa/create-esxi-vm.sh
  scripts/vcsa/create-standalone.sh
  scripts/vcsa/create-vcsa-vm.sh
Labels: cla-not-required

#1131 Change key name according to Datacenter object
  simulator/simulator.go
Labels: area/vcsim, kind/bug

#1132 Avoid recursive root path search in govc find command
  govc/object/find.go
  govc/test/object.bats
Labels: area/govc, cla-not-required, kind/bug

#1133 Add -sharing option to vm.disk.create and vm.disk.attach
  govc/test/vm.bats
  govc/vm/disk/attach.go
  govc/vm/disk/change.go
  govc/vm/disk/create.go
Labels: cla-not-required

#1136 Add VirtualDiskManager wrapper to set UUID
  govc/datastore/disk/create.go
  govc/datastore/disk/info.go
  govc/emacs/govc.el
  govc/test/datastore.bats
  object/virtual_disk_manager.go
  simulator/virtual_disk_manager.go
Labels: cla-not-required

#1140 govc: import.ovf pool flag should be optional if host is specified
  govc/importx/ovf.go
  govc/test/import.bats
Labels: cla-not-required
