Repository vmware/govmomi, pull requests merged in 2019-10, with the labels that each got.

#1641 Fix object.collect with moref argument
  govc/object/collect.go
  govc/test/object.bats
Labels: cla-not-required

#1642 added IsTemplate vm helper
  object/virtual_machine.go
Labels: area/library, kind/enhancement

#1646 Report errors when cdrom.insert fails
  govc/device/cdrom/insert.go
Labels: area/govc, kind/bug

#1647 vcsim: add feature examples
  govc/test/vcsim.bats
  simulator/feature_test.go
Labels: area/vcsim, cla-not-required, documentation/examples

#1644 vslm: Fix to throw errors on tasks that are completed with error state
  vslm/global_object_manager.go
Labels: area/library, cla-not-required, kind/enhancement

#1648 Debug Update to Add a Password Scrubber and stdout style LogType
  govc/README.md
  govc/flags/debug.go
  vim25/debug/debug.go
  vim25/debug/file.go
  vim25/debug/log.go
Labels: area/govc, kind/enhancement

#1653 vcsim: add VirtualMachine.Rename_Task support
  govc/test/object.bats
  simulator/virtual_machine.go
Labels: cla-not-required

#1649 Allow sending multiple characters through -c and name the keys
  govc/USAGE.md
  govc/vm/keystrokes.go
Labels: area/govc, kind/enhancement

#1660 Avoid empty principal in HoK token request
  sts/signer.go
Labels: cla-not-required

#1661 Set stable vSAN client version
  cns/cns_util.go
Labels: cla-not-required

#1623 vcsim: add record/playback functionality
  govc/object/save.go
  govc/test/object.bats
  govc/test/vcsim.bats
  simulator/authorization_manager.go
  simulator/custom_fields_manager.go
  simulator/datacenter.go
  simulator/event_manager.go
  simulator/file_manager.go
  simulator/folder.go
  simulator/host_local_account_manager.go
  simulator/ip_pool_manager.go
  simulator/license_manager.go
  simulator/model.go
  simulator/option_manager.go
  simulator/ovf_manager.go
  simulator/performance_manager.go
  simulator/search_index.go
  simulator/service_instance.go
  simulator/session_manager.go
  simulator/storage_resource_manager.go
  simulator/task_manager.go
  simulator/user_directory.go
  simulator/view_manager.go
  simulator/virtual_disk_manager.go
  simulator/vstorage_object_manager.go
  vcsim/README.md
  vcsim/main.go
  vim25/mo/fixtures/cluster_host_property.xml
  vim25/mo/retrieve.go
  vim25/mo/retrieve_test.go
Labels: cla-not-required

#1662 adding managed obj type to table
  govc/fields/ls.go
Labels: area/govc, kind/enhancement

#1663 vcsim: update docs
  simulator/feature_test.go
  vcsim/README.md
Labels: cla-not-required

#1666 vcsim: simplify container vm arguments input
  govc/test/vcsim.bats
  simulator/container.go
  simulator/feature_test.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1668 vcsim: pass guestinfo vars as env vars to container vms
  govc/test/vcsim.bats
  simulator/container.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1655 govc: add vm.customize command
  govc/flags/list.go
  govc/test/vm.bats
  govc/vm/customize.go
  simulator/customization_spec_manager.go
  simulator/model.go
  simulator/virtual_machine.go
Labels: area/govc, area/vcsim, cla-not-required, kind/feature

#1671 govc: support vm.customize without a managed spec
  govc/test/vm.bats
  govc/vm/customize.go
Labels: area/govc, cla-not-required, kind/enhancement

#1669 govc: fixup usage suggestions
  govc/cli/command.go
  govc/test/cli.bats
Labels: area/govc, cla-not-required

#1672 govc: add vm.power doc
  govc/vm/power.go
Labels: area/govc, cla-not-required, documentation/examples

#1670 Add a method to update ports on a distributed virtual switch
  object/distributed_virtual_switch.go
Labels: area/library, kind/enhancement

#1676 vcsim: don't allow duplicate names for Folder/StoragePod
  govc/test/datastore.bats
  govc/test/folder.bats
  simulator/folder.go
Labels: area/vcsim, cla-not-required, kind/bug

#1678 Avoid possible deadlock in KeepAliveHandler
  session/keep_alive.go
  session/keep_alive_test.go
Labels: area/client, cla-not-required, kind/bug

#1680 Refactor session KeepAlive tests to use vcsim
  session/keep_alive_test.go
Labels: cla-not-required

#1683 Add option to follow all struct fields in mo.References
  vim25/mo/retrieve.go
  vim25/mo/retrieve_test.go
Labels: cla-not-required

#1685 Add nil checks for all HostConfigManager references
  object/host_config_manager.go
  object/host_config_manager_test.go
Labels: area/library, cla-not-required, kind/bug
