Repository vmware/govmomi, pull requests merged in 2019-12, with the labels that each got.

#1730 govc: fix vm.create doc regarding -on flag
  govc/vm/create.go
Labels: cla-not-required

#1732 govc: add datacenter create/delete examples
  govc/datacenter/create.go
Labels: cla-not-required

#1731 examples: add VirtualMachine.Customize
  object/example_test.go
Labels: cla-not-required

#1733 Pass vm.Config.Uuid into the "VM" container via an env var
  simulator/container.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1729 govc: add device.boot -secure flag
  govc/device/boot.go
Labels: area/govc, cla-not-required, kind/enhancement

#1737 examples: add Common.Rename
  object/example_test.go
  simulator/datacenter.go
Labels: cla-not-required, documentation/examples

#1701 Content Library: VM Template support
  govc/cli/register.go
  govc/library/checkin.go
  govc/library/checkout.go
  govc/library/clone.go
  govc/library/deploy.go
  govc/library/info.go
  govc/test/library.bats
  vapi/internal/internal.go
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_vmtx.go
Labels: area/vapi, cla-not-required, kind/feature

#1734 vcsim: bind mount BIOS UUID DMI files
  govc/test/vcsim.bats
  simulator/container.go
  simulator/container_test.go
  simulator/object.go
  simulator/virtual_machine.go
Labels: cla-not-required

#1738 vcsim: remove container volumes
  govc/test/vcsim.bats
  simulator/container.go
  simulator/model.go
Labels: area/vcsim, cla-not-required

#1740 Move to cs.identity service type for sts endpoint
  govc/emacs/govc.el
  govc/sso/service/ls.go
  govc/test/sso.bats
  lookup/simulator/registration_info.go
  lookup/simulator/simulator_test.go
  sts/client.go
Labels: area/client, cla-not-required

#1741 govc: default to simple esxcli format when hints fields is empty
  govc/host/esxcli/esxcli.go
Labels: cla-not-required

#1743 vcsim: automatically set Context.Caller
  simulator/folder.go
  simulator/object.go
  simulator/resource_pool.go
  simulator/simulator.go
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required

#1745 Move to cs.identity service type for sso admin endpoint
  ssoadmin/client.go
Labels: area/client, cla-not-required

#1744 vcsim: avoid possible panic in VirtualMachine.Destroy_Task
  simulator/race_test.go
  simulator/registry.go
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required, kind/bug

#1746 vcsim: Get IP address on non-default container network
  simulator/container.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1747 examples: output VM names in performance example
  performance/example_test.go
Labels: cla-not-required

#1751 VSLM: fixed the missing param in the QueryChangedDiskArea API impl
  vslm/global_object_manager.go
Labels: cla-not-required

#1757 govc: add library.info details
  govc/library/info.go
  vapi/simulator/simulator.go
Labels: area/govc, area/vcsim, cla-not-required, kind/enhancement

#1761 Add library ItemType constants
  govc/library/deploy.go
  govc/library/import.go
  vapi/library/library_item.go
  vapi/simulator/simulator.go
Labels: area/client, area/library, cla-not-required

#1762 govc: handle xsd:string responses
  govc/host/esxcli/esxcli.go
  govc/host/esxcli/response.go
Labels: area/govc, cla-not-required, kind/bug

#1749 vcsim: add -trace-file option
  govc/test/vcsim.bats
  simulator/simulator.go
  vcsim/main.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1758 Add retry support for HTTP status codes
  simulator/simulator.go
  vim25/examples_test.go
  vim25/retry.go
  vim25/soap/client.go
Labels: area/client, area/vcsim, cla-not-required, kind/enhancement

#1763 Added the missing RetrieveSnapshotDetails API in VSLM
  vslm/global_object_manager.go
Labels: cla-not-required

#1752 govc: remove guest.run toolbox dependency
  govc/vm/guest/run.go
  guest/toolbox/client.go
Labels: area/govc, cla-not-required, kind/enhancement

#1765 govc: add optional library.info details
  govc/library/info.go
  govc/test/library.bats
Labels: area/govc, cla-not-required, kind/enhancement

#1767 vcsim: propagate VirtualMachineCloneSpec.Template
  govc/test/library.bats
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required

#1769 govc: fix library.info output formatting
  govc/library/info.go
Labels: area/govc, cla-not-required
