Repository vmware/govmomi, pull requests merged in 2019-11, with the labels that each got.

#1698 vcsim: add vim25 client helper to vapi simulator
  vapi/simulator/simulator.go
Labels: area/vapi, area/vcsim, cla-not-required

#1687 Generate pointer type for ResourceReductionToToleratePercent
  gen/vim_wsdl.rb
  vim25/types/types.go
  vslm/types/types.go
Labels: cla-not-required

#1692 Add MTU flag for DVS creation
  govc/dvs/create.go
Labels: area/govc, kind/enhancement

#1693 Add ability to change a DVS that has already been created
  govc/dvs/change.go
Labels: area/govc, kind/feature

#1696 Add ability to change a vnic on a host
  govc/host/vnic/change.go
Labels: area/govc, kind/feature

#1702 Added SSL Thumbprint option to create
  govc/library/create.go
Labels: area/govc

#1708 Move to Go 1.13
  .travis.yml
  go.mod
Labels: cla-not-required

#1706 govc: add default library.create thumbprint
  vapi/library/library.go
Labels: area/govc, area/vapi, cla-not-required, kind/enhancement

#1714 govc: avoid env for -cluster placement flag
  govc/flags/cluster.go
  govc/vm/clone.go
  govc/vm/create.go
Labels: area/govc, cla-not-required

#1715 vcsim: properly initialize portgroup portKeys field
  govc/test/network.bats
  simulator/dvs.go
Labels: cla-not-required

#1716 govc: add doc on vm.info -r flag
  govc/USAGE.md
  govc/vm/info.go
Labels: cla-not-required, documentation/examples

#1721 vcsim: add Floppy Drive support to OVF manager
  simulator/ovf_manager.go
Labels: area/vcsim, cla-not-required

#1722 Add CustomizationSpecManager.Info method and example
  object/customization_spec_manager.go
  object/example_test.go
Labels: area/library, cla-not-required, documentation/examples

#1723 Revert "gen: retain omitempty field tag with int pointer types"
  gen/vim_wsdl.rb
  vim25/types/types.go
  vslm/types/types.go
Labels: cla-not-required

#1724 vcsim: validate VirtualDisk UnitNumber
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required
