Repository vmware/govmomi, pull requests merged in 2019-06, with the labels that each got.

#1466 govc: add -options support to library.deploy
  govc/importx/options.go
  govc/importx/ova.go
  govc/importx/ovf.go
  govc/importx/spec.go
  govc/library/deploy.go
  govc/test/library.bats
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_ovf.go
Labels: cla-not-required

#1481 govc: increase guest.ps -X poll interval
  govc/vm/guest/ps.go
Labels: area/govc, cla-not-required, kind/bug

#1482 govc: change logs.download -default=false
  govc/logs/download.go
Labels: cla-not-required

#1479 Add library export support
  govc/library/export.go
  govc/library/import.go
  govc/library/session/ls.go
  govc/library/session/rm.go
  govc/test/library.bats
  vapi/internal/internal.go
  vapi/library/library_item_downloadsession_file.go
  vapi/library/library_item_updatesession.go
  vapi/rest/client.go
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_ovf.go
Labels: kind/feature

#1484 Fix json request tracing
  scripts/debug-xmlformat.sh
  vim25/soap/client.go
  vim25/soap/debug.go
Labels: cla-not-required

#1486 govc: add vm.change hot-add options
  govc/vm/change.go
Labels: area/govc, cla-not-required, kind/enhancement

#1491 Fix HostNetworkSystem.QueryNetworkHint return value
  object/host_network_system.go
Labels: area/library, cla-not-required, kind/bug

#1492 Support external PSC lookup service
  lookup/client.go
  lookup/client_test.go
  lookup/simulator/simulator_test.go
  sts/simulator/simulator.go
Labels: area/client, cla-not-required, kind/bug

#1489 vcsim: add support to override credentials
  govc/flags/client.go
  govc/test/vcsim.bats
  session/manager.go
  simulator/session_manager.go
  simulator/simulator.go
  vcsim/main.go
Labels: cla-not-required

#1496 govc: add context to LoadX509KeyPair error
  govc/flags/client.go
Labels: area/govc, cla-not-required, kind/enhancement

#1498 Fix tls config in soap.NewServiceClient
  govc/test/tags.bats
  vim25/soap/client.go
Labels: area/client, kind/bug

#1499 Add method that sets vim version to the endpoint service version
  govc/about/command.go
  govc/flags/client.go
  govc/test/cli.bats
  simulator/simulator.go
  vcsim/main.go
  vim25/client.go
  vim25/soap/client.go
Labels: area/client, cla-not-required, kind/enhancement

#1503 Goreleaser update for multiple archives
  .goreleaser.yml
  Dockerfile.govc
  Dockerfile.vcsim
Labels: cla-not-required

#1501 tags API: add methods for association of multiple tags/objects
  govc/tags/association/ls.go
  govc/test/tags.bats
  vapi/simulator/simulator.go
  vapi/tags/tag_association.go
Labels: area/govc, area/vapi, cla-not-required, kind/enhancement

#1480 Add http source support to library.import
  govc/library/import.go
  govc/test/library.bats
  vapi/library/library_item_updatesession.go
  vapi/library/library_item_updatesession_file.go
  vapi/simulator/simulator.go
Labels: cla-not-required

#1505 Add various govmomi client examples
  event/example_test.go
  find/finder.go
  object/example_test.go
  object/task.go
  property/example_test.go
  simulator/datastore.go
  simulator/model.go
  view/example_test.go
Labels: cla-not-required

#1500 govc: host.vnic.info -json support
  govc/host/vnic/info.go
  govc/test/host.bats
Labels: cla-not-required

#1509 govc: add datastore.info -H flag
  govc/datastore/info.go
  govc/flags/datacenter.go
  govc/object/collect.go
  govc/test/datastore.bats
Labels: area/govc, cla-not-required, kind/enhancement
