Repository vmware/govmomi, pull requests merged in 2019-09, with the labels that each got.

#1582 Content library: support library ID in Finder
  govc/library/deploy.go
  govc/library/errors.go
  govc/library/export.go
  govc/library/import.go
  govc/library/rm.go
  govc/test/library.bats
  vapi/library/finder/finder.go
Labels: cla-not-required

#1579 Add option to propagate MissingSet faults in WaitForUpdates
  property/wait.go
  property/wait_test.go
  simulator/session_manager.go
  task/wait.go
Labels: cla-not-required, kind/bug

#1585 Update generated code to vSphere 6.7u3
  gen/gen.sh
  vim25/mo/mo.go
  vim25/types/types.go
  vslm/methods/methods.go
  vslm/types/types.go
Labels: area/client, cla-not-required, kind/enhancement

#1590 vcsim: DefaultDatastoreID is optional in library deploy
  govc/library/deploy.go
  govc/test/library.bats
  vapi/simulator/simulator.go
Labels: cla-not-required

#1589 vcsim: add PlaceVm support
  govc/test/vm.bats
  govc/vm/clone.go
  govc/vm/create.go
  object/cluster_compute_resource.go
  simulator/cluster_compute_resource.go
Labels: cla-not-required

#1592 Add ResourcePool.Owner method
  object/example_test.go
  object/resource_pool.go
Labels: area/library, cla-not-required, kind/enhancement

#1594 govc: fix datacenter.info against nested folders
  govc/datacenter/info.go
  govc/test/datacenter.bats
Labels: area/govc, cla-not-required, kind/bug

#1595 vcsim: add endpoint registration mechanism
  lookup/client_test.go
  lookup/simulator/simulator.go
  lookup/simulator/simulator_test.go
  pbm/simulator/simulator.go
  simulator/model.go
  simulator/session_manager.go
  simulator/simulator.go
  sts/simulator/simulator.go
  vapi/simulator/simulator.go
  vcsim/main.go
Labels: area/vcsim, cla-not-required, kind/feature

#1597 vcsim: rename Example to Run
  event/example_test.go
  object/example_test.go
  performance/example_test.go
  property/example_test.go
  simulator/model.go
  view/example_test.go
Labels: area/vcsim, cla-not-required

#1596 examples: add VirtualMachine.CreateSnapshot
  object/example_test.go
Labels: cla-not-required, documentation/examples

#1586 vapi: return info with current session query
  vapi/rest/client.go
  vapi/rest/client_test.go
  vapi/simulator/simulator.go
Labels: area/vapi, cla-not-required, kind/enhancement

#1599 vm.keystrokes -s (Allow spaces)
  govc/vm/keystrokes.go
Labels: area/govc, cla-not-required, kind/enhancement

#1602 Add interactiveSession flag
  govc/vm/guest/auth.go
Labels: area/govc, cla-not-required, kind/enhancement

#1603 Check whether there's a NIC before updating guest.ipAddress
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required, kind/bug

#1609 Replace LoadRetrievePropertiesResponse with LoadObjectContent
  property/collector.go
  view/container_view.go
  vim25/mo/retrieve.go
  vim25/mo/retrieve_test.go
Labels: area/library, cla-not-required, kind/enhancement

#1610 vcsim: use TLS in simulator.Run
  simulator/example_test.go
  simulator/model.go
Labels: area/vcsim, cla-not-required

#1613 Fix error check in session.Secret
  session/manager.go
Labels: cla-not-required

#1628 Support HoK tokens with Interactive Users
  sts/signer.go
Labels: cla-not-required

#1629 vapi: expand internal path constants
  vapi/internal/internal.go
Labels: area/vapi, cla-not-required

#1632 vcsim: avoid race in ViewManager
  simulator/session_manager.go
  simulator/view_manager.go
  simulator/view_manager_test.go
Labels: cla-not-required

#1631 vapi: refactor for external API implementations
  simulator/simulator.go
  vapi/internal/internal.go
  vapi/library/library.go
  vapi/library/library_file.go
  vapi/library/library_item.go
  vapi/library/library_item_downloadsession_file.go
  vapi/library/library_item_updatesession.go
  vapi/library/library_item_updatesession_file.go
  vapi/rest/client.go
  vapi/rest/resource.go
  vapi/simulator/simulator.go
  vapi/tags/categories.go
  vapi/tags/tag_association.go
  vapi/tags/tags.go
  vapi/vcenter/vcenter_ovf.go
Labels: area/vapi, area/vcsim, cla-not-required, kind/enhancement

#1633 Ensure that extraConfig from clone spec is added to VM being cloned
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required, kind/bug

#1635 vapi: support DeleteLibrary with subscribed libraries
  vapi/library/library.go
Labels: cla-not-required
