Repository vmware/govmomi, pull requests merged in 2019-08, with the labels that each got.

#1545 Don't limit library.Finder to local libraries
  vapi/library/finder/finder.go
Labels: cla-not-required

#1550 Add v4 option to VirtualMachine.WaitForIP
  govc/vm/ip.go
  object/virtual_machine.go
  object/vm_guest_test.go
Labels: cla-not-required

#1562 Use gnu xargs in bats tests on Darwin
  govc/test/ls.bats
Labels: cla-not-required

#1569 Include url in Client.Download error
  vim25/soap/client.go
Labels: area/client, cla-not-required

#1570 Add simulator.Model.Run example
  simulator/example_test.go
Labels: cla-not-required, documentation/examples

#1572 CNS go bindings
  cns/client.go
  cns/client_test.go
  cns/cns_util.go
  cns/methods/methods.go
  cns/mo/mo.go
  cns/simulator/simulator.go
  cns/simulator/simulator_test.go
  cns/types/enum.go
  cns/types/if.go
  cns/types/types.go
Labels: cla-not-required

#1573 Fix deadlock for keep alive handlers that attempt log in
  session/keep_alive.go
Labels: cla-not-required

#1574 Add content library subscription support
  govc/library/create.go
  govc/library/info.go
  govc/test/library.bats
  vapi/internal/internal.go
  vapi/library/library.go
  vapi/simulator/simulator.go
Labels: area/govc, area/library, cla-not-required, kind/feature

#1575 govc: validate moref argument
  govc/flags/datacenter.go
Labels: area/govc, cla-not-required, kind/bug
