Repository vmware/govmomi, pull requests merged in 2019-07, with the labels that each got.

#1515 Set the InventoryPath of the folder object in DefaultFolder
  find/finder.go
Labels: cla-not-required

#1516 VSLM FCD Global Object Manager client for 6.7U2+
  vslm/client.go
  vslm/global_object_manager.go
Labels: cla-not-required

#1520 examples: add CustomFieldManager.Set
  object/example_test.go
Labels: documentation/examples

#1524 govcsim: Support Default UplinkTeamingPolicy in DVSPG
  simulator/dvs.go
  simulator/folder.go
Labels: area/vcsim, kind/enhancement

#1528 Fixed type bug in global_object_manager Task.QueryResult
  vslm/global_object_manager.go
Labels: cla-not-required

#1534 govc: support library paths in tags.attach commands
  govc/tags/association/attach.go
  govc/tags/association/detach.go
  govc/tags/association/ls.go
  govc/test/library.bats
Labels: area/govc, cla-not-required

#1535 Fix library AddLibraryItemFileFromURI fingerprint
  vapi/library/library_item_updatesession_file.go
Labels: cla-not-required

#1536 Content library related cleanups
  govc/library/deploy.go
  govc/library/export.go
  govc/library/import.go
  scripts/debug-xmlformat.sh
  vapi/library/library.go
  vapi/library/library_file.go
  vapi/library/library_item.go
  vapi/library/library_item_downloadsession_file.go
  vapi/library/library_item_updatesession.go
  vapi/library/library_item_updatesession_file.go
  vapi/rest/client.go
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_ovf.go
Labels: cla-not-required

#1538 govc: add guest.df command
  govc/vm/guest/df.go
Labels: area/govc, kind/feature

#1541 examples: add ExampleVirtualMachine_Reconfigure
  object/example_test.go
Labels: cla-not-required, documentation/examples
