Repository vmware/govmomi, pull requests merged in 2020-05, with the labels that each got.

#1961 Add logic to return default HealthStatus in CnsCreateVolume.
  cns/simulator/simulator.go
Labels: area/vcsim, cla-not-required

#1963 fix a few data races when creating VMs concurrently
  simulator/folder.go
  simulator/virtual_machine.go
Labels: area/vcsim, kind/bug

#1962 govc: support find with -customValue filter
  govc/object/find.go
  govc/test/object.bats
  property/filter.go
Labels: cla-not-required

#1967 simulator: relax some typing constraints
  simulator/folder.go
  simulator/resource_pool.go
  simulator/view_manager.go
Labels: area/vcsim

#1969 simulator: refactor folder children operations
  simulator/cluster_compute_resource.go
  simulator/datacenter.go
  simulator/datastore.go
  simulator/dvs.go
  simulator/entity.go
  simulator/entity_test.go
  simulator/file_manager.go
  simulator/folder.go
  simulator/folder_test.go
  simulator/host_datastore_system.go
  simulator/host_network_system.go
  simulator/host_system.go
  simulator/model.go
  simulator/portgroup.go
  simulator/property_collector_test.go
  simulator/registry.go
  simulator/service_instance.go
  simulator/virtual_machine.go
Labels: area/vcsim

#1952 Add support for attach-tag-to-multiple-objects
  vapi/simulator/simulator.go
  vapi/tags/tag_association.go
Labels: area/vapi, area/vcsim, kind/enhancement

#1973 vapi: sync access to rest.Client.SessionID
  govc/library/export.go
  govc/session/login.go
  govc/session/ls.go
  session/cache/session.go
  vapi/rest/client.go
Labels: area/vapi, cla-not-required

#1957 Add REST session keep alive support
  govc/flags/client.go
  govc/library/deploy.go
  govc/library/import.go
  session/keep_alive.go
  session/keep_alive_test.go
  session/keepalive/example_test.go
  session/keepalive/handler.go
  session/keepalive/handler_test.go
  simulator/session_manager.go
  vapi/simulator/simulator.go
Labels: cla-not-required

#1974 vcsim: modify markdown link at README.md
  vcsim/README.md
Labels: documentation/examples

#1979 go binding for CNS QueryVolumeInfo API
  cns/.gitignore
  cns/client.go
  cns/client_test.go
  cns/methods/methods.go
  cns/simulator/simulator.go
  cns/simulator/simulator_test.go
  cns/types/if.go
  cns/types/types.go
Labels: cla-not-required

#1982 Bump to vSphere version 7
  README.md
  govc/flags/version.go
  govc/test/cli.bats
  govc/vm/create.go
  vim25/client.go
Labels: cla-not-required, documentation/examples

#1985 providing examples for govc guest.run
  govc/USAGE.md
  govc/vm/guest/run.go
Labels: area/govc, documentation/examples

#1987 simulator: fix handling of nil Reference in container walk
  simulator/view_manager.go
Labels: area/vcsim

#1988 vcsim: add lookup ServiceRegistration example
  lookup/simulator/example_test.go
Labels: area/vcsim, cla-not-required, documentation/examples

#1986 Adding subProfileName in pbm.CapabilityProfileCreateSpec
  pbm/pbm_util.go
Labels: cla-not-required

#1997 govc: support raw object references in import.ova NetworkMapping
  govc/importx/ovf.go
  govc/test/import.bats
  govc/test/network.bats
  govc/vm/network/add.go
  list/lister.go
  simulator/dvs.go
Labels: cla-not-required

#1994 Add appliance log forwarding config handler and govc verb
  govc/main.go
  govc/vcsa/log/forwarding.go
  vapi/appliance/logging/forwarding.go
Labels: area/govc, area/vapi, kind/feature
