Repository vmware/govmomi, pull requests merged in 2020-09, with the labels that each got.

#2102 Add AuthorizationManager.HasUserPrivilegeOnEntities wrapper
  object/authorization_manager.go
Labels: cla-not-required

#2095 govc: add vm.console -wss flag
  govc/vm/console.go
Labels: cla-not-required

#2096 govc: add storage.policy commands
  govc/main.go
  govc/storage/policy/create.go
  govc/storage/policy/info.go
  govc/storage/policy/ls.go
  govc/storage/policy/rm.go
  govc/test/storage.bats
  pbm/client.go
  pbm/simulator/simulator.go
Labels: cla-not-required

#2100 vim25/xml: sync with Go 1.15 encoding/xml
  vim25/xml/marshal.go
  vim25/xml/marshal_test.go
  vim25/xml/read.go
  vim25/xml/typeinfo.go
  vim25/xml/xml.go
  vim25/xml/xml_test.go
Labels: cla-not-required

#2104 vcsim: fix ListView.Modify
  simulator/race_test.go
  simulator/registry.go
  simulator/view_manager.go
Labels: area/vcsim, cla-not-required

#2106 sts: fix SignRequest bodyhash for non-empty request body
  sts/signer.go
Labels: cla-not-required

#2105 vapi: add WCP support bundle bindings
  govc/namespace/cluster/logs.go
  govc/test/namespace.bats
  vapi/namespace/internal/internal.go
  vapi/namespace/namespace.go
  vapi/namespace/simulator/simulator.go
  vapi/rest/client.go
Labels: area/govc, area/vapi, area/vcsim, cla-not-required, kind/feature

#2103 govc: add CNS volume ls and rm commands
  cns/simulator/simulator.go
  govc/main.go
  govc/test/volume.bats
  govc/volume/ls.go
  govc/volume/rm.go
  vcsim/main.go
Labels: cla-not-required

#2110 govc: fix vm.clone panic when target VM already exists
  govc/test/vm.bats
  govc/vm/clone.go
Labels: cla-not-required

#2109 govc: support sparse backing in vm.disk.change
  govc/vm/disk/change.go
Labels: area/govc, cla-not-required, kind/bug

#2113 Add ClusterDistribution field for CNS telemetry
  cns/client_test.go
  cns/cns_util.go
  cns/types/types.go
Labels: cla-not-required

#2122 examples: add events
  examples/events/main.go
  examples/examples.go
Labels: cla-not-required, documentation/examples

#2133 vcsim: set VirtualDisk backing option defaults
  govc/test/vm.bats
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required
