Repository vmware/govmomi, pull requests merged in 2020-03, with the labels that each got.

#1851 vcsim: support Folder in RelocateVM spec
  govc/flags/folder.go
  govc/test/vm.bats
  govc/vm/migrate.go
  simulator/virtual_machine.go
Labels: cla-not-required

#1855 vcsim: create vmdk directory if needed
  govc/test/vm.bats
  simulator/virtual_machine.go
  simulator/virtual_machine_test.go
Labels: cla-not-required

#1853 Add Content Library subscriptions support
  govc/flags/library.go
  govc/library/create.go
  govc/library/info.go
  govc/library/publish.go
  govc/library/subscriber/create.go
  govc/library/subscriber/info.go
  govc/library/subscriber/ls.go
  govc/library/subscriber/rm.go
  govc/main.go
  govc/test/library.bats
  vapi/internal/internal.go
  vapi/library/library.go
  vapi/library/library_item.go
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_vmtx.go
Labels: area/govc, area/library, area/vapi, area/vcsim, cla-not-required, kind/feature

#1862 govc: support nested groups in sso.group.update
  govc/sso/group/update.go
  ssoadmin/client.go
Labels: area/govc, cla-not-required

#1874 Avoid possible panic in Filter.MatchProperty
  govc/test/object.bats
  property/filter.go
  simulator/virtual_machine.go
Labels: cla-not-required

#1869 reset all for recursive calls
  govc/vm/customize.go
Labels: cla-not-required

#1876 govc: add vm.change '-memory-pin' flag
  govc/vm/change.go
Labels: cla-not-required

#1880 vcsim: unique MAC address for VM NICs
  govc/test/network.bats
  simulator/virtual_machine.go
Labels: cla-not-required

#1877 Compute Policy support
  govc/compute/policy/create.go
  govc/compute/policy/ls.go
  govc/compute/policy/rm.go
  govc/main.go
  govc/test/compute.bats
  vapi/compute/internal/internal.go
  vapi/compute/policy.go
  vapi/compute/simulator/simulator.go
  vcsim/main.go
Labels: area/govc, area/vapi, area/vcsim, cla-not-required

#1881 Modified return type for Get policy
  vapi/compute/policy.go
Labels: cla-not-required

#1882 govc: support optional compute.policy.ls argument
  govc/compute/policy/ls.go
  vapi/compute/policy.go
Labels: cla-not-required

#1883 govmomi changes for CNS vSphere CSI driver 2.0
  cns/client.go
  cns/client_test.go
  cns/cns_util.go
  cns/methods/methods.go
  cns/simulator/simulator.go
  cns/simulator/simulator_test.go
  cns/types/enum.go
  cns/types/if.go
  cns/types/types.go
  vsan/client.go
  vsan/client_test.go
  vsan/methods/methods.go
  vsan/types/enum.go
  vsan/types/types.go
  vsan/vsanfs/types/enum.go
  vsan/vsanfs/types/types.go
Labels: cla-not-required

#1886 Remove extra err check
  govc/flags/client.go
Labels: cla-not-required

#1885 govc: add import.spec support for remote URLs
  govc/importx/spec.go
  govc/test/import.bats
Labels: area/govc, cla-not-required, kind/enhancement

#1884 vapi: prefer header authn to cookie authn
  govc/library/export.go
  vapi/internal/internal.go
  vapi/rest/client.go
  vapi/simulator/simulator.go
Labels: area/vapi, cla-not-required

#1889 Revert compute policy support
  govc/compute/policy/create.go
  govc/compute/policy/ls.go
  govc/compute/policy/rm.go
  govc/main.go
  govc/test/compute.bats
  vapi/compute/internal/internal.go
  vapi/compute/policy.go
  vapi/compute/simulator/simulator.go
  vcsim/main.go
Labels: cla-not-required

#1888 Fix the types of errors returned from VSLM tasks
  vslm/global_object_manager.go
Labels: cla-not-required

#1891 vcsim: validate session key in TerminateSession method
  govc/test/session.bats
  govc/test/vcsim.bats
  simulator/session_manager.go
Labels: area/vcsim, cla-not-required
