Repository vmware/govmomi, pull requests merged in 2020-01, with the labels that each got.

#1711 Add ability to set DVS discovery protocol on create and change
  govc/dvs/change.go
  govc/dvs/create.go
Labels: cla-rejected

#1773 govc: guest.run improvements
  govc/cli/command.go
  govc/vm/guest/guest.go
  govc/vm/guest/run.go
  guest/file_manager.go
  guest/toolbox/client.go
  toolbox/toolbox-test.sh
Labels: area/govc, cla-not-required

#1771 govc: add vm.customize multiple IP support
  govc/test/vm.bats
  govc/vm/customize.go
  simulator/virtual_machine.go
Labels: area/govc, cla-not-required

#1777 govc: add 5.0 to vm.create hardware version map
  govc/vm/create.go
Labels: cla-not-required

#1776 Clarify System.Read privilege requirement for PortGroup backing
  object/distributed_virtual_portgroup.go
  object/distributed_virtual_portgroup_test.go
Labels: cla-not-required

#1770 Add Content Library synchronization support
  govc/library/sync.go
  govc/test/library.bats
  vapi/internal/internal.go
  vapi/library/library.go
  vapi/library/library_item.go
  vapi/simulator/simulator.go
  vapi/vcenter/vcenter_vmtx.go
Labels: area/govc, area/library, area/vapi, area/vcsim, cla-not-required

#1778 Clarify DVS EthernetCardBackingInfo error message
  object/distributed_virtual_switch.go
  object/distributed_virtual_switch_test.go
Labels: cla-not-required

#1780 govc: guest -i flag only applies to ProcessManager
  govc/vm/guest/auth.go
  govc/vm/guest/getenv.go
  govc/vm/guest/guest.go
  govc/vm/guest/kill.go
  govc/vm/guest/ps.go
  govc/vm/guest/run.go
  govc/vm/guest/start.go
Labels: area/govc, cla-not-required

#1781 Update docs for 0.22 release
  .mailmap
  CHANGELOG.md
  CONTRIBUTORS
  govc/CHANGELOG.md
  govc/USAGE.md
  govc/datastore/info.go
  govc/library/clone.go
Labels: cla-not-required

#1784 vapi: Add cluster modules client and simulator
  vapi/cluster/cluster.go
  vapi/cluster/cluster_test.go
  vapi/cluster/internal/internal.go
  vapi/cluster/simulator/simulator.go
  vcsim/main.go
Labels: area/vapi, area/vcsim, cla-not-required, kind/feature

#1786 vapi: add CreateTag example
  vapi/tags/example_test.go
Labels: area/vapi, cla-not-required, documentation/examples

#1787 Add finder example for MultipleFoundError
  find/example_test.go
Labels: cla-not-required, documentation/examples

#1792 Fix AttributeValue.C14N for 6.7u3
  sts/client_test.go
  sts/internal/types.go
Labels: cla-not-required

#1793 Release version 0.22.1
  CHANGELOG.md
  govc/CHANGELOG.md
  govc/flags/version.go
Labels: cla-not-required

#1789 Add permissions for NoCryptoAdmin
  simulator/esx/authorization_manager.go
Labels: area/vcsim

#1795 Avoid encoding/xml import
  Makefile
  vim25/client.go
Labels: cla-not-required

#1796 examples: add ContainerView.Find
  view/example_test.go
Labels: cla-not-required, documentation/examples

#1799 vcsim: add support for NSX backed networks
  object/opaque_network.go
  object/opaque_network_test.go
  simulator/dvs.go
  simulator/example_test.go
  simulator/folder.go
  simulator/model.go
  simulator/model_test.go
  simulator/portgroup.go
  simulator/portgroup_test.go
  vcsim/main.go
  vim25/types/types.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1790 fix simulator disk manager fault message.
  simulator/virtual_disk_manager.go
Labels: area/vcsim

#1237 govc: save sessions using sha256 ID
  govc/flags/client.go
Labels: area/govc

#1801 govc: add find -l flag
  govc/object/find.go
  govc/test/object.bats
Labels: area/govc, cla-not-required, kind/enhancement

#1802 vcsim: add docs on generated inventory names
  simulator/model.go
  vcsim/README.md
Labels: area/vcsim, cla-not-required, documentation/examples

#1804 govc: output formatting enhancements
  govc/cli/command.go
  govc/flags/output.go
  govc/test/cli.bats
  govc/test/vm.bats
Labels: area/govc, cla-not-required, kind/feature

#1808 Simplify ObjectName method
  object/common.go
  object/common_test.go
  object/network.go
Labels: cla-not-required

#1800 Update vim25/xml to Go v1.13.6
  vim25/xml/LICENSE
  vim25/xml/atom_test.go
  vim25/xml/example_test.go
  vim25/xml/marshal.go
  vim25/xml/marshal_test.go
  vim25/xml/read.go
  vim25/xml/read_test.go
  vim25/xml/typeinfo.go
  vim25/xml/xml.go
  vim25/xml/xml_test.go
Labels: area/client, cla-not-required, kind/quality

#1815 govc: add object.collect -o flag
  govc/object/collect.go
  govc/test/object.bats
Labels: area/govc, area/vcsim, cla-not-required, kind/enhancement

#1816 vcsim: support tags with the same name
  govc/test/tags.bats
  vapi/simulator/simulator.go
Labels: area/vcsim, cla-not-required, kind/bug

#1817 govc: fix doc for -g flag (guest id) choices
  govc/vm/create.go
  govc/vm/option/info.go
Labels: area/govc, cla-not-required

#1818 vcsim: avoid possible panic in UnregisterVM_Task
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required, kind/bug
