Repository vmware/govmomi, pull requests merged in 2020-12, with the labels that each got.

#1558 Added Instant Clone feature
  govc/USAGE.md
  govc/flags/datastore.go
  govc/flags/folder.go
  govc/flags/resource_pool.go
  govc/vm/instantclone.go
  object/virtual_machine.go
Labels: area/govc, kind/feature

#2199 govc: add volume.ls -ds option
  govc/volume/ls.go
Labels: cla-not-required

#2184 Add vSAN 7.0 U1 API bindings
  vsan/client.go
  vsan/methods/methods.go
  vsan/methods/retrieve.go
  vsan/mo/mo.go
  vsan/types/enum.go
  vsan/types/if.go
  vsan/types/types.go
Labels: cla-not-required

#2197 Add Configure ACL go bindings
  cns/client.go
  cns/methods/methods.go
  cns/types/types.go
Labels: cla-not-required

#2206 examples: add Folder.CreateVM
  object/example_test.go
Labels: cla-not-required

#2207 govc: add cluster.usage command
  govc/cluster/usage.go
  govc/test/cluster.bats
Labels: area/govc, cla-not-required, kind/feature

#2211 Add batch APIs for multiple tags to object
  vapi/simulator/simulator.go
  vapi/tags/errors.go
  vapi/tags/tag_association.go
  vapi/tags/tag_association_test.go
Labels: area/vapi, cla-not-required, kind/feature

#2205 Add function to get vsan host config
  vsan/client.go
  vsan/client_test.go
Labels: cla-not-required

#2214 vcsim: include stderr in log message when volume import fails
  simulator/container.go
Labels: area/vcsim, cla-not-required

#2215 Update docs for 0.24 release
  .mailmap
  .travis.yml
  CHANGELOG.md
  CONTRIBUTORS
  govc/CHANGELOG.md
  govc/USAGE.md
  govc/build.sh
  govc/device/pci/add.go
  govc/device/pci/remove.go
  govc/flags/version.go
  govc/namespace/cluster/disable.go
  govc/namespace/cluster/enable.go
  govc/vm/instantclone.go
Labels: cla-not-required

#2219 Fix DvsNetworkRuleQualifier interface
  govc/dvs/portgroup/info.go
  vim25/types/if.go
Labels: cla-not-required

#2220 vcsim: fixes for PowerCLI Get-VirtualNetwork
  gen/vim_wsdl.rb
  govc/test/vcsim.bats
  simulator/folder.go
  simulator/model.go
  sts/simulator/simulator.go
  vim25/types/types.go
Labels: area/vcsim, cla-not-required
