Repository vmware/govmomi, pull requests merged in 2020-04, with the labels that each got.

#1903 govc: avoid truncation in object.collect
  govc/object/collect.go
  property/wait.go
Labels: cla-not-required

#1904 govc: enable library.checkout and library.checkin by default
  govc/library/checkin.go
  govc/library/checkout.go
  govc/test/library.bats
Labels: area/govc, cla-not-required, kind/feature

#1905 govc: add vm.change -uuid flag
  govc/test/vm.bats
  govc/vm/change.go
Labels: cla-not-required

#1906 govc: add guest directory upload/download examples
  govc/vm/guest/download.go
  govc/vm/guest/upload.go
Labels: cla-not-required

#1901 vcsim: VM templates do not have a ResourcePool
  govc/test/vm.bats
  simulator/virtual_machine.go
Labels: cla-not-required

#1907 vcsim: support QueryConfigOptionEx GuestId param
  govc/test/vm.bats
  simulator/environment_browser.go
  simulator/virtual_machine.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1898 Refactor govc session persistence into session/cache package
  govc/about/cert.go
  govc/flags/client.go
  govc/session/login.go
  govc/session/logout.go
  govc/sso/client.go
  govc/sso/user/id.go
  govc/test/session.bats
  session/cache/example_test.go
  session/cache/session.go
  vapi/rest/client.go
  vim25/client.go
Labels: cla-not-required

#1912 govc: remove ClientFlag.WithRestClient
  govc/flags/client.go
  govc/library/checkin.go
  govc/library/checkout.go
  govc/library/clone.go
  govc/library/cp.go
  govc/library/create.go
  govc/library/deploy.go
  govc/library/export.go
  govc/library/import.go
  govc/library/info.go
  govc/library/ls.go
  govc/library/publish.go
  govc/library/rm.go
  govc/library/session/ls.go
  govc/library/session/rm.go
  govc/library/subscriber/create.go
  govc/library/subscriber/info.go
  govc/library/subscriber/ls.go
  govc/library/subscriber/rm.go
  govc/library/sync.go
  govc/tags/association/attach.go
  govc/tags/association/detach.go
  govc/tags/association/ls.go
  govc/tags/category/create.go
  govc/tags/category/info.go
  govc/tags/category/ls.go
  govc/tags/category/rm.go
  govc/tags/category/update.go
  govc/tags/create.go
  govc/tags/info.go
  govc/tags/ls.go
  govc/tags/rm.go
  govc/tags/update.go
Labels: area/govc, cla-not-required

#1917 vcsim: fix flaky library subscriber test
  vapi/simulator/simulator.go
Labels: area/vcsim, cla-not-required, kind/bug

#1914 Add non-null HostLicensableResourceInfo to HostSystem
  simulator/esx/host_system.go
Labels: area/vcsim

#1916 govc: ignore ManagedObjectNotFound errors in 'find' command
  govc/object/find.go
Labels: cla-not-required

#1915 vcsim: avoid panic if ovf:capacityAllocationUnits is not present
  govc/test/import.bats
  simulator/ovf_manager.go
Labels: cla-not-required

#1918 govc: add session.ls -r flag
  govc/flags/client.go
  govc/session/ls.go
  govc/test/session.bats
Labels: area/govc, cla-not-required, kind/enhancement

#1926 govc: fix host.info CPU usage
  govc/host/info.go
Labels: cla-not-required

#1921 Default to separate session cache directories
  session/cache/session.go
Labels: cla-not-required

#1930 vcsim: fixes for PowerCLI
  govc/test/sso.bats
  lookup/simulator/registration_info.go
  lookup/simulator/simulator.go
  lookup/simulator/simulator_test.go
  simulator/event_manager.go
  simulator/event_manager_test.go
Labels: area/vcsim, cla-not-required, kind/bug

#1924 vcsim: validate DVS membership
  simulator/virtual_machine.go
  simulator/virtual_machine_fault_test.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#1932 Fix delegated Holder-of-Key token signature
  sts/internal/types.go
  vim25/xml/read.go
Labels: cla-not-required

#1933 Avoid possible nil pointer dereference in guest TransferURL
  guest/file_manager.go
  guest/file_manager_test.go
Labels: cla-not-required

#1934 govc: add REST support for session.login -cookie flag
  govc/session/login.go
  govc/test/session.bats
Labels: area/govc, area/vapi, cla-not-required

#1929 vcsim: apply ExtraConfig after devices
  govc/test/vcsim.bats
  simulator/virtual_machine.go
Labels: cla-not-required

#1937 govc: add session.login -X flag
  govc/session/login.go
  govc/test/session.bats
  vapi/rest/client.go
Labels: area/govc, area/vapi, cla-not-required, kind/enhancement

#1938 govc: vm.clone ResourcePool is optional when -cluster is specified
  govc/vm/clone.go
Labels: cla-not-required

#1939 vcsim: traverse configManager.networkSystem in object.save
  govc/object/save.go
  govc/test/vcsim.bats
Labels: cla-not-required

#1941 Add GetProfileNameByID functionality to PBM
  pbm/client.go
  pbm/client_test.go
Labels: area/client, cla-not-required, kind/enhancement

#1942 Add BackingDiskUrlPath and CnsAlreadyFault go bindings to CNS APIs
  cns/client.go
  cns/client_test.go
  cns/cns_util.go
  cns/types/if.go
  cns/types/types.go
Labels: cla-not-required

#1943 Add retry tests for CNS Create API with backingdiskUrlPath and fix CNS binding for CnsAlreadyRegisteredFault
  cns/client_test.go
  cns/cns_util.go
  cns/types/types.go
Labels: cla-not-required

#1946 vcsim: add AuthorizationManager.HasPrivilegeOnEntities
  simulator/authorization_manager.go
Labels: cla-not-required

#1922 Update to vSphere 7 APIs
  gen/gen.sh
  pbm/types/enum.go
  vim25/methods/methods.go
  vim25/mo/mo.go
  vim25/types/enum.go
  vim25/types/if.go
  vim25/types/types.go
  vslm/methods/methods.go
  vslm/types/enum.go
  vslm/types/types.go
Labels: cla-not-required

#1954 govc: add -version flag to datastore.create command
  govc/datastore/create.go
Labels: cla-not-required

#1958 govc: support VirtualApp with -pool flag
  govc/flags/resource_pool.go
  govc/importx/ovf.go
  govc/test/import.bats
  simulator/ovf_manager.go
  simulator/resource_pool.go
Labels: cla-not-required
