Repository vmware/govmomi, pull requests merged in 2020-06, with the labels that each got.

#2001 provided examples for vm.clone and host.esxcli
  govc/USAGE.md
  govc/host/esxcli/esxcli.go
  govc/vm/clone.go
Labels: area/govc, documentation/examples

#2012 vapi: use header authentication in file Upload/Download
  govc/library/export.go
  govc/library/import.go
  govc/test/library.bats
  vapi/rest/client.go
Labels: cla-not-required

#2014 Update docs for 0.23 release
  .mailmap
  .travis.yml
  CHANGELOG.md
  CONTRIBUTORS
  README.md
  govc/CHANGELOG.md
  govc/README.md
  govc/USAGE.md
  govc/host/esxcli/esxcli.go
  govc/object/save.go
  govc/session/login.go
  govc/usage.sh
  govc/vm/guest/run.go
  vcsim/README.md
Labels: cla-not-required, documentation/examples

#2009 examples: add property.Collector.Retrieve example
  property/example_test.go
Labels: cla-not-required, documentation/examples

#2015 vcsim: add PbmQueryAssociatedProfile method
  pbm/simulator/simulator.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#2026 vcsim: use HostNetworkSystem wrapper with -load flag
  govc/test/vcsim.bats
  simulator/host_network_system.go
  simulator/model.go
Labels: cla-not-required

#2017 vcsim: set HostSystem IP in cluster AddHost_Task
  govc/test/cluster.bats
  simulator/host_system.go
  simulator/object.go
  simulator/object_test.go
Labels: cla-not-required

#2032 vcsim: add HostNetworkSystem.QueryNetworkHint
  simulator/host_network_system.go
  simulator/host_network_system_test.go
Labels: cla-not-required
