Repository vmware/govmomi, pull requests merged in 2020-07, with the labels that each got.

#2041 added support for returning array of BaseCnsVolumeOperationResult for QueryVolumeInfo API
  cns/client_test.go
  cns/cns_util.go
Labels: cla-not-required

#2044 check if config isn't nil before returning an uuid
  object/virtual_machine.go
Labels: cla-not-required

#2040 vapi: add initial support for namespace management
  govc/main.go
  govc/namespace/cluster/ls.go
  govc/test/namespace.bats
  vapi/namespace/internal/internal.go
  vapi/namespace/namespace.go
  vapi/namespace/simulator/simulator.go
  vapi/rest/client.go
  vapi/simulator/simulator.go
  vcsim/main.go
Labels: area/govc, area/vapi, area/vcsim, cla-not-required, kind/feature

#2055 vapi: add Content Library example
  vapi/library/example_test.go
Labels: cla-not-required

#2057 Setting hardware properties in clone VM spec from template VM
  simulator/virtual_machine.go
Labels: area/vcsim

#2062 bats: test fixes for running on MacOSX
  govc/test/library.bats
  govc/test/network.bats
  govc/test/test_helper.bash
  govc/test/vcsim.bats
Labels: cla-not-required

#2021 Vsan Performance Data Collection API
  vsan/client.go
Labels: cla-not-required

#2056 vcsim: fix save/load property collection for VmwareDistributedVirtual…
  govc/object/save.go
  simulator/dvs.go
  simulator/model.go
  simulator/property_collector.go
  vim25/types/helpers.go
Labels: cla-not-required

#2067 Add ExtendDisk and InflateDisk wrappers to vlsm/object_manager
  vslm/object_manager.go
Labels: cla-not-required

#2068 Add AttachDisk and DetachDisk wrappers for the virtualMachine object.
  object/virtual_machine.go
Labels: cla-not-required

#2063 vapi: add tags.Manager.GetAttachedTagsOnObjects example
  vapi/tags/example_test.go
Labels: cla-not-required, documentation/examples

#2069 vcsim: avoid ViewManager.ModifyListView race
  simulator/race_test.go
  simulator/view_manager.go
Labels: area/vcsim, cla-not-required
