Repository vmware/govmomi, pull requests merged in 2021-08, with the labels that each got.

#2540 vcsim: avoid race when fetching object Locker
  simulator/registry.go
  simulator/task.go
Labels: kind/bug, cla-not-required, area/vcsim

#2541 Fix for issue 2539
  govc/vm/rdm/attach.go
Labels: kind/bug, area/govc

#2547 fix: Regenerated interface and type to include BaseAgencyConfigInfo. …
  eam/object/agency.go
  eam/object/esx_agent_manager.go
  eam/simulator/agency.go
  eam/simulator/esx_agent_manager.go
  eam/types/if.go
  eam/types/types.go
  gen/gen.sh
  gen/vim_wsdl.rb
Labels: cla-not-required

#2557 vcsim: check if VM host InMaintenanceMode
  govc/test/vm.bats
  simulator/virtual_machine.go
Labels: kind/enhancement, cla-not-required, area/vcsim
