Repository vmware/govmomi, pull requests merged in 2021-05, with the labels that each got.

#2400 Clarify SetRootCAs behavior
  vim25/soap/client.go
Labels: cla-not-required

#2407 Add issue greeting
  .github/comment-template.md
  .github/workflows/issue-greeting.yaml
Labels: cla-not-required, kind/enhancement

#2405 docs: Document linker and GOFLAGS for build vars
  govc/README.md
  vcsim/README.md
Labels: cla-not-required, documentation

#2404 Add WIP Action
  .github/workflows/govmomi-check-wip.yaml
Labels: cla-not-required

#2403 Remove dep files
  Gopkg.lock
  Gopkg.toml
Labels: cla-not-required

#2415 Use "vcsim uuidgen" for bats tests
  govc/test/vcsim.bats
  govc/test/vm.bats
Labels: cla-not-required

#2417 Update govc test docs with act
  govc/test/README.md
Labels: cla-not-required

#2413 Only greet unassociated users
  .github/workflows/issue-greeting.yaml
Labels: cla-not-required

#2411 Add chore section to CHANGELOG
  .chglog/config.yml
  .github/comment-template.md
  CONTRIBUTING.md
Labels: cla-not-required

#2426 fix: Isolate SSO govc tests
  .github/workflows/govmomi-govc-tests.yaml
  Makefile
  govc/test/sso.bats
Labels: cla-not-required

#2427 vcsim: avoid edit device panic when DeviceInfo is nil
  simulator/virtual_machine.go
  simulator/virtual_machine_test.go
Labels: area/vcsim, cla-not-required, kind/bug

#2433 vcsim: include all namespaces in /about info
  govc/test/vcsim.bats
  simulator/simulator.go
Labels: area/vcsim, cla-not-required

#2436 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-not-required

#2435 govc: Add support for getting the VC proxy and no-proxy configuration
  govc/main.go
  govc/vcsa/proxy/proxy.go
  vapi/appliance/networking/proxy.go
Labels: area/govc, area/vapi, cla-not-required, kind/feature

#2391 ESX Agent Manager (EAM) Client & Simulator
  eam/README.md
  eam/client.go
  eam/eam.go
  eam/internal/internal.go
  eam/methods/methods.go
  eam/mo/agency.go
  eam/mo/agent.go
  eam/mo/eam_object.go
  eam/mo/esx_agent_manager.go
  eam/object/agency.go
  eam/object/agency_test.go
  eam/object/agent.go
  eam/object/eam_object.go
  eam/object/esx_agent_manager.go
  eam/object/object_test.go
  eam/simulator/README.md
  eam/simulator/agency.go
  eam/simulator/agent.go
  eam/simulator/eam_object.go
  eam/simulator/esx_agent_manager.go
  eam/simulator/issue.go
  eam/simulator/simulator.go
  eam/simulator/simulator_test.go
  eam/simulator/utils.go
  eam/types/enum.go
  eam/types/if.go
  eam/types/types.go
  gen/.gitignore
  gen/gen.sh
  gen/vim_wsdl.rb
  simulator/container.go
  simulator/internal/object_lock.go
  simulator/registry.go
  vcsim/main.go
Labels: cla-not-required

#2449 Fix data race in simulator.container.id
  simulator/container.go
Labels: cla-not-required

#2448 Setup CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: cla-not-required

#2452 chore: Add make help target
  Makefile
Labels: cla-not-required

#2437 Modify QueryAsyncVolume API unit test to be invoked only for vSphere 7.0.3 and above
  cns/client_test.go
Labels: cla-not-required

#2456 Support pre-auth handlers in vC Sim
  eam/simulator/agent.go
  eam/simulator/simulator.go
  eam/simulator/simulator_test.go
  simulator/registry.go
  simulator/simulator.go
Labels: cla-not-required

#2454 Add support for golangci-lint
  .github/workflows/govmomi-go-lint.yaml
  .golangci.yml
  Makefile
  govc/cluster/rule/info_flag.go
  govc/flags/debug.go
  govc/flags/output.go
  hack/tools/.gitignore
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  lookup/simulator/registration_info.go
  object/opaque_network_test.go
  pbm/simulator/simulator.go
  program.mk
  simulator/cluster_compute_resource.go
  simulator/folder.go
  simulator/model.go
  simulator/object.go
  simulator/portgroup_test.go
  simulator/resource_pool_test.go
  simulator/service_instance.go
  simulator/session_manager.go
  simulator/simulator.go
  simulator/virtual_disk_manager.go
  simulator/virtual_disk_manager_test.go
  simulator/virtual_machine.go
  simulator/vstorage_object_manager.go
  sts/signer.go
  vapi/cluster/simulator/simulator.go
  vapi/namespace/simulator/simulator.go
  vapi/simulator/simulator.go
  vcsim/main.go
  vslm/client_test.go
Labels: cla-not-required

#2459 docs: Add blog to `vcsim` README
  vcsim/README.md
Labels: cla-not-required

#2455 Add CNS Snapshot APIs in govmomi/cns
  cns/client.go
  cns/client_test.go
  cns/methods/methods.go
  cns/types/if.go
  cns/types/types.go
Labels: cla-not-required

#2461 Update generated types to vCenter 7.0U2 HP4 (build 17986435)
  eam/types/enum.go
  eam/types/types.go
  gen/gen.sh
  pbm/methods/methods.go
  pbm/types/enum.go
  pbm/types/if.go
  pbm/types/types.go
  sms/methods/methods.go
  sms/types/enum.go
  sms/types/if.go
  sms/types/types.go
  vim25/methods/methods.go
  vim25/mo/mo.go
  vim25/types/enum.go
  vim25/types/if.go
  vim25/types/types.go
  vslm/methods/methods.go
  vslm/types/enum.go
  vslm/types/if.go
  vslm/types/types.go
Labels: cla-not-required

#2462 Update GitHub Test Action to use Makefile
  .github/workflows/govmomi-go-tests.yaml
  Makefile
Labels: cla-not-required

#2463 chore: Add and reorder commits in CHANGELOG
  .chglog/CHANGELOG.tpl.md
  CHANGELOG.md
Labels: cla-not-required

#2451 govc: fix default guest.run path for unsupported Windows guests
  govc/vm/guest/guest.go
  govc/vm/guest/run.go
Labels: cla-not-required

#2428 vcsim: untie datastore capacity from local fs
  simulator/datastore.go
  simulator/host_datastore_system.go
  simulator/model.go
  simulator/os_unix.go
  simulator/os_windows.go
Labels: cla-not-required

#2464 examples: add toolbox Client.Run
  govc/vm/guest/download.go
  govc/vm/guest/guest.go
  govc/vm/guest/run.go
  govc/vm/guest/upload.go
  guest/toolbox/client.go
  guest/toolbox/example_test.go
  simulator/model.go
Labels: cla-not-required, documentation/examples

#2469 Protect FileProvider.files to avoid concurrent access
  vim25/debug/file.go
Labels: cla-not-required

#2474 chore: Fix CONTRIB link in greeting
  .github/comment-template.md
Labels: cla-not-required
