Repository vmware/govmomi, pull requests merged in 2021-12, with the labels that each got.

#2678 fix: govc vm.destroy only destroys the 1st argument
  govc/test/vm.bats
  govc/vm/destroy.go
Labels: kind/bug, cla-not-required, area/govc

#2676 Add `IsAlreadyExists` error helper
  vim25/types/fault.go
Labels: area/library

#2683 Update workflow Go versions
  .github/workflows/govmomi-build.yaml
  .github/workflows/govmomi-go-lint.yaml
  .github/workflows/govmomi-go-tests.yaml
  .github/workflows/govmomi-govc-tests.yaml
  .github/workflows/govmomi-release.yaml
Labels: cla-not-required

#2684 govc: Require full or absolute paths
  govc/flags/datacenter.go
  govc/test/fields.bats
Labels: cla-not-required

#2682 vcsim: add support for cloning HostSystems
  govc/test/vcsim.bats
  simulator/cluster_compute_resource.go
  simulator/host_system.go
Labels: kind/enhancement, cla-not-required, area/vcsim
