Repository vmware/govmomi, pull requests merged in 2021-01, with the labels that each got.

#2225 Updated projects to include VMware Event Broker Appliance
  README.md
Labels: cla-not-required

#2173 vcsim: switch bats tests from esx to vcsim env
  govc/test/device.bats
  govc/test/events.bats
  govc/test/host.bats
  govc/test/metric.bats
  govc/test/network.bats
  govc/test/pool.bats
  govc/test/tasks.bats
  govc/test/test_helper.bash
  govc/test/vcsim.bats
  govc/test/vm.bats
  simulator/feature_test.go
  simulator/resource_pool.go
  simulator/virtual_machine.go
  toolbox/command_test.go
  toolbox/hgfs/server_test.go
Labels: area/vcsim, cla-not-required, kind/enhancement

#2226 vcsim: fix EventHistoryCollector fixes
  simulator/event_manager.go
  simulator/event_manager_test.go
  simulator/race_test.go
Labels: cla-not-required

#2223 examples: add NetworkReference.EthernetCardBackingInfo
  object/example_test.go
  object/virtual_device_list.go
Labels: cla-not-required

#2229 vcsim: record/replay EnvironmentBrowser.QueryConfigOption
  govc/object/save.go
  simulator/environment_browser.go
Labels: cla-not-required

#2232 vcsim: escape datastore name
  simulator/datastore.go
Labels: cla-not-required

#2236 vcsim: move product suffix in ServiceContent.About
  govc/about/command.go
  govc/test/vcsim.bats
  simulator/dvs_manager.go
  simulator/esx/event_manager.go
  simulator/model.go
  simulator/virtual_disk_manager.go
  simulator/virtual_machine.go
  vcsim/main.go
Labels: cla-not-required

#2233 vcsim: use linked list for EventHistoryCollector
  simulator/event_manager.go
  simulator/event_manager_test.go
Labels: area/vcsim, cla-not-required

#2245 vcsim: support EventFilterSpec.Time
  examples/events/main.go
  simulator/event_manager.go
Labels: cla-not-required

#2251 Update ConfigureVolumeACLs bindings in cns types
  cns/client_test.go
  cns/types/types.go
Labels: cla-not-required

#2253 govc: various doc updates
  govc/device/info.go
  govc/library/checkin.go
  govc/library/checkout.go
  govc/library/clone.go
  govc/license/remove.go
  govc/vm/markasvm.go
  govc/volume/rm.go
Labels: cla-not-required

#2250 Little fix for "govc-env --save without config name"
  scripts/govc-env.bash
Labels: area/govc

#2254 Update volume ACL spec to add delete field
  cns/client_test.go
  cns/types/types.go
Labels: cla-not-required

#2255 govc: fix session curl when given a URL query
  govc/session/login.go
  govc/test/session.bats
Labels: area/govc, cla-not-required, documentation/examples, kind/bug

#2256 Remove duplicate cns bindings from vsan directory
  vsan/methods/methods.go
  vsan/mo/mo.go
  vsan/types/enum.go
  vsan/types/if.go
  vsan/types/types.go
Labels: cla-not-required
