Repository vmware/govmomi, pull requests merged in 2021-07, with the labels that each got.

#2507 [feature] govc: Allow cluster.change to set ClusterDrsConfigInfo.vmotionRate
  govc/cluster/change.go
Labels: cla-not-required

#2515 examples: Add Property `Wait()` example
  property/example_test.go
Labels: cla-not-required

#2511 vcsim: propagate CustomizeVM MacAddress to Virtual NIC
  govc/test/vm.bats
  simulator/virtual_machine.go
Labels: cla-not-required

#2525 govc: support updating items in library.update command
  govc/library/update.go
  govc/test/library.bats
  vapi/library/library_item.go
Labels: area/govc, kind/enhancement

#2526 vcsim: use 'domain-c' prefix for cluster moids
  govc/test/object.bats
  simulator/registry.go
Labels: area/vcsim, cla-not-required
