Repository vmware/govmomi, pull requests merged in 2021-04, with the labels that each got.

#2336 govc: add session.ls -S flag
  govc/flags/debug.go
  govc/session/ls.go
  govc/test/session.bats
Labels: area/govc, cla-not-required

#2342 Add action to block WIP PRs
  .github/workflows/govmomi-check-wip.yaml
Labels: cla-not-required

#2343 govc: add library.update command
  govc/library/update.go
  govc/test/library.bats
  vapi/library/library.go
Labels: cla-not-required

#2340 First step towards release automation
  .github/workflows/govmomi-build.yaml
  .github/workflows/govmomi-check-wip.yaml
  .github/workflows/govmomi-go-lint.yaml
  .github/workflows/govmomi-go-tests.yaml
  .github/workflows/govmomi-govc-tests.yaml
  .github/workflows/govmomi-stale.yaml
  .goreleaser.yml
  Dockerfile.vcsim
  Makefile
  README.md
  go.mod
  govc/USAGE.md
  govc/build.sh
  govc/flags/client.go
  govc/flags/version.go
  govc/flags/version_test.go
  govc/test/vcsim.bats
  govc/version/command.go
  program.mk
  vcsim/README.md
  vcsim/main.go
  vendor/modules.txt
Labels: cla-not-required

#2358 vcsim: add moid value mapping mappings
  govc/test/object.bats
  simulator/registry.go
Labels: area/vcsim, cla-not-required

#2359 Logging related updates
  govc/flags/debug.go
  govc/importx/ovf.go
  govc/test/import.bats
  simulator/host_datastore_browser.go
  simulator/http_nfc_lease.go
  simulator/property_collector.go
  simulator/simulator.go
Labels: cla-not-required

#2357 Add action to automate release
  .github/workflows/govmomi-build.yaml
  .github/workflows/govmomi-release.yaml
  .goreleaser.yml
Labels: cla-not-required

#2360 govc: update test images URL
  govc/test/images/update.sh
Labels: cla-not-required

#2362 Add Cron Docker Login Action
  .github/workflows/govmomi-build.yaml
  .github/workflows/verify-docker-login.yaml
Labels: cla-not-required

#2363 govc: add vm.customize -dns-suffix flag
  govc/test/vm.bats
  govc/vm/customize.go
Labels: cla-not-required

#2364 docs: update for 0.25 release
  .mailmap
  CONTRIBUTORS
  govc/CHANGELOG.md
  govc/USAGE.md
  govc/cluster/override/change.go
  govc/cluster/stretch.go
  govc/dvs/portgroup/add.go
  govc/vm/network/change.go
Labels: cla-not-required

#2367 Fix folder write for govc container
  Dockerfile.govc
Labels: cla-not-required

#2371 Exclude go files in release tarball
  .goreleaser.yml
Labels: cla-not-required

#2375 toolbox: move process management to its own package
  toolbox/command.go
  toolbox/command_test.go
  toolbox/process/process.go
  toolbox/process/process_test.go
  toolbox/service_test.go
Labels: cla-not-required

#2380 Increase govc tests timeout
  .github/workflows/govmomi-govc-tests.yaml
Labels: cla-not-required

#2377 Add RELEASE documentation
  RELEASE.md
  govc/release.sh
  static/release-workflow.png
Labels: cla-not-required

#2382 Fix VM Guest test and vet warnings
  object/vm_guest_test.go
Labels: cla-not-required

#2383 Add bindings for CnsQueryAsyncVolume API
  cns/client.go
  cns/client_test.go
  cns/methods/methods.go
  cns/types/types.go
Labels: cla-not-required

#2376 Update READMEs with artifacts and Docker images
  README.md
  govc/README.md
  vcsim/README.md
Labels: cla-not-required, documentation

#2388 Simplify binary download instructions
  govc/README.md
  vcsim/README.md
Labels: cla-not-required

#2386 Remove Travis CI
  .travis.yml
  govc/test/test_helper.bash
  simulator/feature_test.go
  vcsim/main.go
Labels: cla-not-required

#2389 Add queryAsyncVolume in simulator
  cns/simulator/simulator.go
  cns/simulator/simulator_test.go
Labels: cla-not-required

#2395 Add NotFoundFault in cns types
  cns/types/types.go
Labels: cla-not-required

#2396 Automate and update CHANGELOG handling
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/govmomi-build.yaml
  .github/workflows/govmomi-release.yaml
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  RELEASE.md
  go.mod
  go.sum
  govc/CHANGELOG.md
  govc/README.md
  govc/release.sh
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: cla-not-required

#2372 vcsim: add guest operations process support
  govc/test/guest.bats
  govc/test/test_helper.bash
  govc/test/vcsim.bats
  govc/test/vm.bats
  simulator/container.go
  simulator/guest_operations_manager.go
  simulator/guest_operations_manager_test.go
  simulator/virtual_machine.go
  toolbox/hgfs/hgfs_freebsd.go
  toolbox/process/process.go
Labels: area/vcsim, cla-not-required, kind/enhancement
