Repository vmware/govmomi, pull requests merged in 2021-03, with the labels that each got.

#2292 vcsim: fix Task.Info.Entity in RevertToSnapshot_Task
  govc/test/snapshot.bats
  simulator/snapshot.go
Labels: cla-not-required

#2303 Marshal soapFaultError as JSON
  vim25/soap/error.go
Labels: cla-not-required

#2312 govc: fix vm.migrate search index flags
  govc/flags/host_system.go
  govc/test/vm.bats
Labels: area/govc, cla-not-required, kind/bug

#2311 Drop clusterDistribution from vSAN 7.0 update and create spec elements
  cns/cns_util.go
Labels: cla-not-required

#2313 govc: metric command enhancements and fixes
  govc/metric/info.go
  govc/metric/interval/info.go
  govc/metric/ls.go
  govc/metric/performance.go
  govc/metric/sample.go
  govc/test/metric.bats
  performance/manager.go
Labels: area/govc, cla-not-required

#2319 Add client_test for vslm package to validate register disk method
  vslm/client_test.go
Labels: cla-not-required

#2263 govc: add '-trace' and '-verbose' flags
  govc/README.md
  govc/flags/client.go
  govc/flags/debug.go
  govc/importx/spec.go
  govc/test/cli.bats
  govc/test/import.bats
  govc/usage.sh
  scripts/debug-format.sh
  scripts/debug-xmlformat.sh
  vim25/debug/debug.go
  vim25/debug/log.go
  vim25/soap/client.go
  vim25/soap/debug.go
Labels: area/govc, cla-not-required, kind/feature

#2291 Fixes in SOAP download progress
  vim25/progress/reader.go
  vim25/soap/client.go
Labels: area/govc, kind/bug

#2323 Fix events example
  examples/events/main.go
  examples/examples.go
Labels: cla-not-required

#2307 Use Github Actions
  .github/workflows/govmomi-go-build.yaml
  .github/workflows/govmomi-go-lint.yaml
  .github/workflows/govmomi-go-test.yaml
  .github/workflows/govmomi-stale.yaml
Labels: cla-not-required

#2327 Add the vSAN stretched cluster reference.
  vsan/client.go
Labels: cla-not-required

#2329 govc: remove device.boot -firmware default
  govc/device/boot.go
  govc/test/device.bats
Labels: area/govc, cla-not-required

#2332 Use Github Actions Status Badges
  README.md
Labels: cla-not-required

#2328 Add chainable RoundTripper support to endpoint clients
  cns/client.go
  cns/client_test.go
  cns/cns_util.go
  govc/flags/client.go
  govc/flags/debug.go
  govc/namespace/cluster/enable.go
  govc/session/login.go
  govc/sso/client.go
  govc/sso/service/ls.go
  govc/storage/policy/create.go
  govc/storage/policy/info.go
  govc/storage/policy/ls.go
  govc/storage/policy/rm.go
  govc/test/cli.bats
  govc/volume/ls.go
  govc/volume/rm.go
  lookup/client.go
  pbm/client.go
  ssoadmin/client.go
  sts/client.go
  vsan/client.go
  vsan/client_test.go
Labels: cla-not-required

#2335 Add godoc and mod version badges
  README.md
Labels: cla-not-required

#2333 govc: include sub task fault messages on failure
  govc/flags/output.go
  govc/test/cli.bats
  nfc/lease.go
  simulator/virtual_machine.go
  task/error.go
  task/wait.go
Labels: cla-not-required

#2330 Add a stretched cluster conversion command.
  govc/cluster/stretch.go
Labels: cla-not-required

#1636 The tree command
  go.mod
  go.sum
  govc/object/tree.go
  govc/test/object.bats
  vendor/github.com/a8m/tree/.gitignore
  vendor/github.com/a8m/tree/.travis.yml
  vendor/github.com/a8m/tree/LICENSE
  vendor/github.com/a8m/tree/README.md
  vendor/github.com/a8m/tree/color.go
  vendor/github.com/a8m/tree/compileall.sh
  vendor/github.com/a8m/tree/csort_bsd.go
  vendor/github.com/a8m/tree/csort_generic.go
  vendor/github.com/a8m/tree/csort_unix.go
  vendor/github.com/a8m/tree/modes_bsd.go
  vendor/github.com/a8m/tree/modes_unix.go
  vendor/github.com/a8m/tree/modes_unsupported.go
  vendor/github.com/a8m/tree/node.go
  vendor/github.com/a8m/tree/sort.go
  vendor/github.com/a8m/tree/stat_unix.go
  vendor/github.com/a8m/tree/stat_unsupported.go
  vendor/modules.txt
  view/container_view.go
Labels: area/govc, cla-not-required, kind/feature

#2337 vcsim: add vsan simulator
  govc/test/cluster.bats
  simulator/simulator.go
  vcsim/main.go
  vsan/simulator/simulator.go
Labels: area/vcsim, cla-not-required, kind/enhancement
