Repository vmware/govmomi, pull requests merged in 2022-01, with the labels that each got.

#2668 govc: add support for supervisor services deploy
  govc/USAGE.md
  govc/main.go
  govc/namespace/service/activate.go
  govc/namespace/service/create.go
  govc/namespace/service/deactivate.go
  govc/namespace/service/info.go
  govc/namespace/service/ls.go
  govc/namespace/service/rm.go
  govc/test/namespace.bats
  vapi/namespace/internal/internal.go
  vapi/namespace/simulator/simulator.go
  vapi/namespace/supervisorsvc.go
  vapi/simulator/simulator.go
Labels: cla-not-required

#2691 Added vm::ExportSnapshot and snapshot flag to export.ovf
  govc/USAGE.md
  govc/export/ovf.go
  object/virtual_machine.go
Labels: cla-not-required

#2701 fix: Add IPv6 support for signing HTTP request
  go.mod
  sts/signer.go
  sts/signer_test.go
Labels: cla-not-required

#2704 vcsim: copy device list when cloning a VM
  govc/test/vm.bats
  simulator/virtual_machine.go
Labels: kind/bug, cla-not-required, area/vcsim

#2709 Update CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: cla-rejected

#2721 Add Appliance shutdown API
  govc/USAGE.md
  govc/main.go
  govc/test/vcsa_shutdown.bats
  govc/vcsa/shutdown/cancel.go
  govc/vcsa/shutdown/get.go
  govc/vcsa/shutdown/poweroff.go
  govc/vcsa/shutdown/reboot.go
  vapi/appliance/shutdown/shutdown.go
  vapi/simulator/simulator.go
Labels: cla-not-required
