Repository vmware/govmomi, pull requests merged in 2024-07, with the labels that each got.

#3479 api: Add ExtendVirtualDisk method on VirtualDiskManager
  govc/USAGE.md
  govc/datastore/disk/extend.go
  object/virtual_disk_manager.go
  simulator/virtual_disk_manager.go
  simulator/virtual_disk_manager_test.go
Labels: cla-not-required

#3481 api: change CoresPerNumaNode to a pointer type
  gen/vim_wsdl.rb
  vim25/types/types.go
Labels: cla-not-required

#3482 api: GetVirtualDiskInfoByUUID for getting capacity/size info
  vmdk/disk_info.go
  vmdk/disk_info_test.go
  vmdk/import.go
  vmdk/import_test.go
Labels: cla-not-required

#3484 api: Add simulator test for GetVirtualDiskInfoByUUID
  vmdk/disk_info.go
  vmdk/disk_info_test.go
Labels: cla-not-required

#3488 vcsim: Add support for DRS automation levels
  simulator/cluster_compute_resource.go
  simulator/cluster_compute_resource_test.go
Labels: cla-not-required

#3492 chore: fix codeql
  .github/workflows/codeql-analysis.yml
Labels: cla-not-required, github_actions

#3491 refactor: make importing templates available as a lib
  go.mod
  go.sum
  govc/flags/output.go
  govc/importx/options.go
  govc/importx/ova.go
  govc/importx/ovf.go
  govc/importx/spec.go
  govc/library/import.go
  ovf/importer/archive.go
  ovf/importer/importable.go
  ovf/importer/importer.go
  ovf/importer/options.go
  ovf/importer/options_test.go
  ovf/importer/spec.go
  scripts/license.sh
  vim25/progress/loger.go
Labels: cla-not-required

#3500 vcsim: add VmCompatibilityChecker and VmProvisioningChecker
  .github/workflows/govmomi-govc-tests.yaml
  .github/workflows/govmomi-release.yaml
  go.mod
  govc/USAGE.md
  govc/flags/output.go
  govc/main.go
  govc/test/vm.bats
  govc/vm/check/compat.go
  govc/vm/check/config.go
  govc/vm/check/flag.go
  govc/vm/check/relocate.go
  govc/vm/clone.go
  govc/vm/create.go
  govc/vm/migrate.go
  object/vm_compatability_checker.go
  object/vm_provisioning_checker.go
  simulator/esx/host_capability.go
  simulator/host_system.go
  simulator/model.go
  simulator/registry.go
  simulator/resource_pool.go
  simulator/virtual_machine.go
  simulator/vm_compatibility_checker.go
  simulator/vm_compatibility_checker_test.go
  simulator/vm_provisioning_checker.go
  simulator/vm_provisioning_checker_test.go
Labels: cla-not-required

#3458 api: add sata controller
  govc/vm/create.go
  object/virtual_device_list.go
Labels: kind/enhancement, cla-not-required, area/govc

#3502 api: use CheckTestType in compat and provisioning checkers
  govc/vm/check/compat.go
  govc/vm/check/config.go
  govc/vm/check/flag.go
  govc/vm/check/relocate.go
  object/vm_compatability_checker.go
  object/vm_provisioning_checker.go
Labels: cla-not-required

#3505 implement capacityAllocationUnits parser
  ovf/parser.go
  ovf/parser_test.go
Labels: cla-not-required
